/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kr_syeyoung_dungeonsguide_mod_dungeon_actions_route_DPTSP */

#ifndef _Included_kr_syeyoung_dungeonsguide_mod_dungeon_actions_route_DPTSP
#define _Included_kr_syeyoung_dungeonsguide_mod_dungeon_actions_route_DPTSP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kr_syeyoung_dungeonsguide_mod_dungeon_actions_route_DPTSP
 * Method:    runTSPNative
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_kr_syeyoung_dungeonsguide_mod_dungeon_actions_route_DPTSP_runTSPNative
        (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
