name: Build Binaries for Multiple Architectures

on:
  push:
    branches:
      - main

jobs:
  build:
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        include:
          - flag: -DCMAKE_CXX_FLAGS="-m32" -DCMAKE_CXX_COMPILER=i686-w64-mingw32-g++ -DCMAKE_CXX_FLAGS="-static"
            binary: ./build/libdptsp.so
            upload_name: x86_dptsp.dll
          - flag: -DCMAKE_CXX_FLAGS="-m64" -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++ -DCMAKE_CXX_FLAGS="-static"
            binary: ./build/libdptsp.so
            upload_name: x86_64_dptsp.dll
          - flag: -DCMAKE_CXX_FLAGS="-m32" -DCMAKE_CXX_COMPILER=g++-14
            binary: ./build/libdptsp.so
            upload_name: x86_libdptsp.so
          - flag: -DCMAKE_CXX_FLAGS="-m64" -DCMAKE_CXX_COMPILER=g++-14
            binary: ./build/libdptsp.so
            upload_name: x86_64_libdptsp.so
          - flag: -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++-14
            binary: ./build/libdptsp.so
            upload_name: aarch64_libdptsp.so
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Dep
        shell: bash
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install g++-14 gcc-14 g++-mingw-w64-i686 g++-mingw-w64-x86-64 gcc-14-multilib g++-14-multilib linux-libc-dev linux-libc-dev:i386 libc6-i386 libc6-dev-i386 g++-14-aarch64-linux-gnu  gcc-14-aarch64-linux-gnu linux-libc-dev
      - name: Build
        shell: bash
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ${{matrix.flag}} ..
          cmake --build ./

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ${{ matrix.upload_name }}
          path: ${{ matrix.binary }}
  build-win-arm:
    runs-on: windows-11-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build
        shell: bash
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -A ARM64 ..  
          cmake --build ./   --config Release
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: aarch64_dptsp.dll
          path: ./build/Release/dptsp.dll