name: Build Binaries for Multiple Architectures

on:
  push:
    branches:
      - main

jobs:
  build:
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        include:
          - os: windows-latest
            flag: -DCMAKE_CXX_FLAGS="-m32" -G 'MinGW Makefiles'
            binary: ./build/dptsp.dll
            upload_name: x86_64_dptsp.dll
            compiler: gcc
          - os: windows-latest
            flag: -DCMAKE_CXX_FLAGS="-m64" -G 'MinGW Makefiles'
            binary: ./build/dptsp.dll
            upload_name: x64_dptsp.dll
          - os: ubuntu-24.04
            flag: -DCMAKE_CXX_FLAGS="-m32"
            binary: ./build/libdptsp.so
            upload_name: x86_64_libdptsp.so
          - os: ubuntu-24.04
            flag: -DCMAKE_CXX_FLAGS="-m64"
            binary: ./build/libdptsp.so
            upload_name: x64_libdptsp.so
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: gcc-14
          cmake: true
      - name: Build
        shell: bash
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ${{matrix.flag}} ..
          cmake --build ./

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ${{ matrix.upload_name }}
          path: ${{ matrix.binary }}
