name: Build Binaries for Multiple Architectures

on:
  push:
    branches:
      - main

jobs:
  build:
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        include:
          - flag: -DCMAKE_CXX_FLAGS="-m32" -DCMAKE_CXX_COMPILER=i686-w64-mingw32-g++
            binary: ./build/libdptsp.so
            upload_name: x86_64_dptsp.dll
          - flag: -DCMAKE_CXX_FLAGS="-m64" -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++
            binary: ./build/libdptsp.so
            upload_name: x64_dptsp.dll
          - flag: -DCMAKE_CXX_FLAGS="-m32"
            binary: ./build/libdptsp.so
            upload_name: x86_64_libdptsp.so
          - flag: -DCMAKE_CXX_FLAGS="-m64"
            binary: ./build/libdptsp.so
            upload_name: x64_libdptsp.so
          - flag: -DCMAKE_CXX_FLAGS="-m64" -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++
            binary: ./build/libdptsp.so
            upload_name: aarch64_libdptsp.so
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Dep
        shell: bash
        run: |
          sudo apt-get install g++-14 gcc-14 g++-mingw-w64-i686 g++-mingw-w64-x86-64 gcc-multilib g++-multilib libc6-dev-i386 g++-aarch64-linux-gnu
      - name: Build
        shell: bash
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ${{matrix.flag}} ..
          cmake --build ./

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ${{ matrix.upload_name }}
          path: ${{ matrix.binary }}